version: "3.0"

services:
  hub:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - HUB_PORT=8080
      - HUB_NOTIFY_THREADS=2

  web-sub-client:
    image: modfin/websub-client:latest
    ports:
      - "8081:8080"
    environment:
      - HOSTNAME=web-sub-client
      - PORT=8080
      - HUB_URL=http://hub:8080
      - TOPIC=/a/topic
    depends_on:
      - hub
